#!/bin/bash
set -e

# Required env vars
: "${VITE_COMMIT_SHA?Need to set VITE_COMMIT_SHA}"
: "${VITE_AUTH_SERVER_URL?Need to set VITE_AUTH_SERVER_URL}"
: "${VITE_JIRA_CLIENT_ID?Need to set VITE_JIRA_CLIENT_ID}"
: "${VITE_JIRA_SCOPE?Need to set VITE_JIRA_SCOPE}"
: "${VITE_JIRA_CALLBACK_URL?Need to set VITE_JIRA_CALLBACK_URL}"
: "${VITE_JIRA_API_URL?Need to set VITE_JIRA_API_URL}"
: "${VITE_JIRA_APP_KEY?Need to set VITE_JIRA_APP_KEY}"
: "${VITE_STATUS_REPORTS_ENV?Need to set VITE_STATUS_REPORTS_ENV}"
: "${BACKEND_SENTRY_DSN?Need to set BACKEND_SENTRY_DSN}"

cat <<EOF > .env
VITE_COMMIT_SHA=$VITE_COMMIT_SHA
VITE_AUTH_SERVER_URL=$VITE_AUTH_SERVER_URL
VITE_JIRA_CLIENT_ID=$VITE_JIRA_CLIENT_ID
VITE_JIRA_SCOPE=$VITE_JIRA_SCOPE
VITE_JIRA_CALLBACK_URL=$VITE_JIRA_CALLBACK_URL
VITE_JIRA_API_URL=$VITE_JIRA_API_URL
VITE_JIRA_APP_KEY=$VITE_JIRA_APP_KEY
VITE_STATUS_REPORTS_ENV=$VITE_STATUS_REPORTS_ENV
VITE_FRONTEND_SENTRY_DSN=$VITE_FRONTEND_SENTRY_DSN
BACKEND_SENTRY_DSN=$BACKEND_SENTRY_DSN
EOF

# Need repo_env for ec2-deploy
cp .env repo_env

echo ".env and repo_env created at $(pwd)"
cat .env
