import type { Report, Reports } from '../fetcher';
import type { ReportsBackend } from './types';

import { createCodeBlock, createParagraph, findCodeBlockText } from '../../storage/adf';

/**
 * The banner above the payload. A Reports Space work item is an ordinary issue, so anyone with Edit
 * Issues can type into its description — this says what will happen to that typing.
 */
const GENERATED_BANNER = 'Generated by Status Reports for Jira. Edits here are overwritten.';

/**
 * Summary prefix on a tombstoned report. Human-facing and, more usefully, JQL-facing: an admin can
 * clear the litter with `project = X AND summary ~ "[Deleted]"` whenever they feel like it.
 */
const TOMBSTONE_PREFIX = '[Deleted] ';

/** Just the Jira calls this backend makes, so a test can hand it three functions. */
export type SpaceReportsJira = {
  fetchAllJiraIssuesWithJQL(params: { jql: string; fields: string[] }): Promise<unknown[]>;
  createJiraIssue(fields: Record<string, unknown>): Promise<{ id: string; key: string }>;
  editJiraIssueWithNamedFields(issueIdOrKey: string, fields: Record<string, unknown>): Promise<unknown>;
};

export type SpaceReportsConfig = {
  spaceName: string;
  spaceType: string;
};

/**
 * The payload as it sits in a description: the whole `Report`, plus one key only this module knows
 * about. `deleted` is an envelope flag, not part of a report — it is stripped on the way out, so it
 * can never ride along into a later write.
 */
type StoredReport = Report & { deleted?: boolean };

interface SearchedIssue {
  id?: string | number;
  key?: string;
  fields?: {
    summary?: string;
    description?: unknown;
  };
}

/** JQL string literals are double-quoted, so a key containing one would otherwise break the query. */
const escapeJqlValue = (value: string): string => value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

const buildDescription = (report: StoredReport) => ({
  type: 'doc',
  version: 1,
  content: [createParagraph(GENERATED_BANNER), createCodeBlock(JSON.stringify(report, null, 2))],
});

/**
 * One work item per saved report, inside a space the user nominates.
 *
 * **Identity.** The payload written into the description is the whole `Report`, `id` included, so
 * ids round-trip and report-of-reports references (`{type:'saved-report', params:{reportId}}`) keep
 * resolving with no mapping table. The Jira issue key is only an address: it lives in an in-memory
 * map filled by `readAll`, never in the report.
 *
 * See spec/026-storage-saved-reports/plan.md § Space backend details.
 */
export const createSpaceReportsBackend = (
  jira: SpaceReportsJira,
  { spaceName, spaceType }: SpaceReportsConfig,
): ReportsBackend => {
  /** `report.id` → Jira issue key. Rebuilt by every `readAll`; kept current by every write. */
  const issueKeyById = new Map<string, string>();

  /**
   * Whether the map was ever built from the space itself. Once it has been, a miss means the report
   * really isn't there: its id was minted locally, so no other client can have written it. Without
   * this, migrating *n* reports would re-list the space once per report — every one of them is a
   * miss by definition.
   */
  let hasListed = false;

  /**
   * A report whose description isn't parseable JSON is skipped, never thrown. One hand-mangled
   * description must not blank the whole list — that is the failure mode this storage option trades
   * for being readable, and it is scoped to the one report either way.
   */
  const parseReport = (issue: SearchedIssue): Report | null => {
    const address = issue.key ?? String(issue.id ?? 'unknown');
    const text = findCodeBlockText(issue.fields?.description);

    if (!text) {
      console.warn(`[reports/storage] ${address} has no JSON block in its description; skipping it`);

      return null;
    }

    let parsed: unknown;

    try {
      parsed = JSON.parse(text);
    } catch (error) {
      console.warn(`[reports/storage] could not parse the saved report in ${address}; skipping it`, error);

      return null;
    }

    if (!parsed || typeof parsed !== 'object') {
      console.warn(`[reports/storage] the JSON block in ${address} is not a saved report; skipping it`);

      return null;
    }

    const { deleted, ...report } = parsed as StoredReport;

    if (typeof report.id !== 'string' || !report.id) {
      console.warn(`[reports/storage] the saved report in ${address} has no id; skipping it`);

      return null;
    }

    // A tombstone, not a problem — silent. See `remove` for why deletion writes one of these.
    if (deleted) {
      return null;
    }

    // The payload is authoritative — it is what round-trips. Summary and `queryParams` are only
    // backstops for a record someone assembled by hand.
    return {
      ...report,
      name: report.name || issue.fields?.summary || report.id,
      queryParams: report.queryParams ?? '',
    };
  };

  const listReports = async (): Promise<Reports> => {
    const issues = (await jira.fetchAllJiraIssuesWithJQL({
      jql: `project = "${escapeJqlValue(spaceName)}" AND issuetype = "${escapeJqlValue(spaceType)}" ORDER BY updated DESC`,
      // Raw field ids rather than the named-field variant the configuration issue uses: `summary`
      // and `description` are system fields whose ids are the same on every site, so this needs
      // nothing from the field catalog to have loaded.
      fields: ['summary', 'description'],
    })) as SearchedIssue[];

    issueKeyById.clear();
    hasListed = true;

    const reports: Reports = {};

    for (const issue of issues) {
      const report = parseReport(issue);

      if (!report) {
        continue;
      }

      const address = issue.key ?? (issue.id === undefined ? undefined : String(issue.id));

      if (!address) {
        console.warn(`[reports/storage] a work item in ${spaceName} came back with no key; skipping it`);

        continue;
      }

      // ORDER BY updated DESC, so if two work items somehow claim the same report the newest wins.
      if (reports[report.id]) {
        continue;
      }

      reports[report.id] = report;
      issueKeyById.set(report.id, address);
    }

    return reports;
  };

  /** The work item holding `reportId`, listing the space first if this session never has. */
  const findIssueKey = async (reportId: string): Promise<string | undefined> => {
    const known = issueKeyById.get(reportId);

    if (known) {
      return known;
    }

    if (!hasListed) {
      // An empty map would otherwise create a second work item for a report another client (or the
      // other host — both can point at the same space) already wrote. This is what makes re-running
      // a half-finished migration repair it rather than duplicate it.
      await listReports();
    }

    return issueKeyById.get(reportId);
  };

  const upsert = async (report: Report): Promise<void> => {
    const issueKey = await findIssueKey(report.id);

    if (issueKey) {
      await jira.editJiraIssueWithNamedFields(issueKey, {
        Summary: report.name,
        Description: buildDescription(report),
      });

      return;
    }

    const created = await jira.createJiraIssue({
      project: { key: spaceName },
      issuetype: { name: spaceType },
      summary: report.name,
      description: buildDescription(report),
    });

    const address = created?.key ?? created?.id;

    if (address) {
      issueKeyById.set(report.id, address);
    }
  };

  return {
    readAll: listReports,
    upsert,
    /**
     * **Deletion is a tombstone, not a `DELETE`.** The work item is edited to carry `deleted: true`
     * and a `[Deleted]` summary, and `readAll` skips it — so the report is gone everywhere
     * immediately, including on the other host if both point at this space.
     *
     * Why not really delete it: a Connect app's `DELETE` scope is separate from `write`, so a real
     * delete would need a descriptor change and every existing install to re-approve it. The
     * alternatives are worse — transitioning to Done depends on each project's workflow (available
     * transitions, required fields on the transition screen), and archiving is Jira Premium only.
     * Tombstoning is the same edit `upsert` already makes, so it needs no permission the app doesn't
     * already require to save a report at all.
     *
     * The cost is litter: tombstoned work items stay in the space. `TOMBSTONE_PREFIX` is what makes
     * them findable in bulk when someone wants to clear them out for real.
     */
    remove: async (report) => {
      const issueKey = await findIssueKey(report.id);

      if (!issueKey) {
        console.warn(`[reports/storage] no work item in ${spaceName} holds "${report.name}"; nothing to delete`);

        return;
      }

      await jira.editJiraIssueWithNamedFields(issueKey, {
        Summary: `${TOMBSTONE_PREFIX}${report.name}`,
        Description: buildDescription({ ...report, deleted: true }),
      });

      issueKeyById.delete(report.id);
    },
    // Sequential rather than parallel: this runs at most once per install and every call may create
    // a work item, so a burst of concurrent writes buys nothing and risks the rate limiter.
    writeMigrated: async (migrated) => {
      for (const report of migrated) {
        await upsert(report);
      }
    },
    // A space needs no initialization — unlike the web build's configuration issue, the user
    // nominated an existing one and the pointer was only written once it was confirmed reachable.
    canWrite: async () => true,
  };
};
