import type { Report } from '../fetcher';
import type { SpaceReportsJira } from './space';

import { createSpaceReportsBackend } from './space';

const config = { spaceName: 'STATREPS', spaceType: 'Story' };

const gantt: Report = { id: 'gantt', name: 'Gantt', queryParams: 'primaryReportType=start-due' };
const table: Report = { id: 'table', name: 'Table', queryParams: 'primaryReportType=table' };

/** A work item as the space backend writes it: a banner paragraph, then the report as JSON. */
const issueFor = (key: string, report: Report) => ({
  key,
  fields: {
    summary: report.name,
    description: {
      type: 'doc',
      version: 1,
      content: [
        { type: 'paragraph', content: [{ type: 'text', text: 'Generated by Status Reports for Jira.' }] },
        { type: 'codeBlock', attrs: { language: 'json' }, content: [{ type: 'text', text: JSON.stringify(report) }] },
      ],
    },
  },
});

const makeJira = (issues: unknown[] = []) => {
  let nextKey = 1;

  const jira = {
    fetchAllJiraIssuesWithJQL: vi.fn(async () => issues),
    createJiraIssue: vi.fn(async () => {
      const key = `STATREPS-${100 + nextKey++}`;

      return { id: String(1000 + nextKey), key };
    }),
    editJiraIssueWithNamedFields: vi.fn(async () => undefined),
  };

  return jira as unknown as SpaceReportsJira & typeof jira;
};

/** The report the backend wrote into a description, read back out of the call it made. */
const writtenReport = (description: any): Report => {
  const codeBlock = description.content.find((node: any) => node.type === 'codeBlock');

  return JSON.parse(codeBlock.content[0].text);
};

describe('the reports space backend', () => {
  beforeEach(() => {
    vi.spyOn(console, 'warn').mockImplementation(() => {});
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('reads a report out of a code block, keyed by the id in the payload', async () => {
    const jira = makeJira([issueFor('STATREPS-1', gantt), issueFor('STATREPS-2', table)]);

    await expect(createSpaceReportsBackend(jira, config).readAll()).resolves.toEqual({ gantt, table });
  });

  it('scopes the search to the configured space and type', async () => {
    const jira = makeJira();

    await createSpaceReportsBackend(jira, config).readAll();

    expect(jira.fetchAllJiraIssuesWithJQL).toHaveBeenCalledWith({
      jql: 'project = "STATREPS" AND issuetype = "Story" ORDER BY updated DESC',
      fields: ['summary', 'description'],
    });
  });

  // The failure mode this storage option trades for being readable: a description is editable by
  // anyone with Edit Issues. One mangled item must cost one report, not the whole list.
  it('skips a report it cannot parse rather than throwing', async () => {
    const mangled = issueFor('STATREPS-9', table);
    mangled.fields.description.content[1].content[0].text = '{ not json';

    const jira = makeJira([issueFor('STATREPS-1', gantt), mangled]);

    await expect(createSpaceReportsBackend(jira, config).readAll()).resolves.toEqual({ gantt });
    expect(console.warn).toHaveBeenCalled();
  });

  it('skips a work item with no code block at all', async () => {
    const empty = { key: 'STATREPS-9', fields: { summary: 'Notes', description: { type: 'doc', content: [] } } };
    const jira = makeJira([issueFor('STATREPS-1', gantt), empty]);

    await expect(createSpaceReportsBackend(jira, config).readAll()).resolves.toEqual({ gantt });
  });

  it('edits the work item a known report already lives in', async () => {
    const jira = makeJira([issueFor('STATREPS-1', gantt)]);
    const backend = createSpaceReportsBackend(jira, config);
    const renamed = { ...gantt, name: 'Delivery Gantt' };

    await backend.readAll();
    await backend.upsert(renamed, { gantt: renamed });

    expect(jira.createJiraIssue).not.toHaveBeenCalled();
    expect(jira.editJiraIssueWithNamedFields).toHaveBeenCalledTimes(1);

    const [issueKey, fields] = jira.editJiraIssueWithNamedFields.mock.calls[0] as [string, any];

    expect(issueKey).toBe('STATREPS-1');
    expect(fields.Summary).toBe('Delivery Gantt');
    expect(writtenReport(fields.Description)).toEqual(renamed);
  });

  it('creates a work item for a report it has never seen', async () => {
    const jira = makeJira();
    const backend = createSpaceReportsBackend(jira, config);

    await backend.upsert(gantt, { gantt });

    expect(jira.editJiraIssueWithNamedFields).not.toHaveBeenCalled();
    expect(jira.createJiraIssue).toHaveBeenCalledTimes(1);

    const [fields] = jira.createJiraIssue.mock.calls[0] as [any];

    expect(fields.project).toEqual({ key: 'STATREPS' });
    expect(fields.issuetype).toEqual({ name: 'Story' });
    expect(fields.summary).toBe('Gantt');
    // The whole record, id included — that is what makes ids round-trip and report-of-reports
    // references keep resolving with no mapping table.
    expect(writtenReport(fields.description)).toEqual(gantt);
  });

  // Two hosts can point at the same space, so "not in my map" never means "not in the space".
  it('re-lists before creating, so a stale map cannot duplicate a report', async () => {
    const jira = makeJira([issueFor('STATREPS-1', gantt)]);
    const backend = createSpaceReportsBackend(jira, config);

    await backend.upsert(gantt, { gantt });

    expect(jira.fetchAllJiraIssuesWithJQL).toHaveBeenCalledTimes(1);
    expect(jira.createJiraIssue).not.toHaveBeenCalled();
    expect(jira.editJiraIssueWithNamedFields).toHaveBeenCalledTimes(1);
  });

  // Otherwise migrating n reports lists the space n times — every one of them is a miss by
  // definition, and the first list already answered the question for all of them.
  it('lists the space once for a burst of reports it has never seen', async () => {
    const jira = makeJira();
    const backend = createSpaceReportsBackend(jira, config);

    await backend.upsert(gantt, { gantt });
    await backend.upsert(table, { gantt, table });

    expect(jira.fetchAllJiraIssuesWithJQL).toHaveBeenCalledTimes(1);
    expect(jira.createJiraIssue).toHaveBeenCalledTimes(2);
  });

  // Deletion is a tombstone: a Connect app's DELETE scope is separate from `write`, so a real
  // DELETE would need a descriptor change and every install to re-approve it. Tombstoning is the
  // same edit `upsert` already makes.
  it('tombstones the work item a report lives in instead of deleting it', async () => {
    const jira = makeJira([issueFor('STATREPS-1', gantt)]);
    const backend = createSpaceReportsBackend(jira, config);

    await backend.readAll();
    await backend.remove(gantt, {});

    const [issueKey, fields] = jira.editJiraIssueWithNamedFields.mock.calls[0] as [string, any];

    expect(issueKey).toBe('STATREPS-1');
    // Prefixed so `summary ~ "[Deleted]"` finds the litter for a bulk clean-up later.
    expect(fields.Summary).toBe('[Deleted] Gantt');
    expect(writtenReport(fields.Description)).toMatchObject({ id: 'gantt', deleted: true });
  });

  // The read filter is what actually makes it gone — and it is shared, so both hosts pointed at one
  // space agree the moment the edit lands.
  it('does not list a tombstoned report', async () => {
    const tombstone = issueFor('STATREPS-9', { ...table, deleted: true } as typeof table);
    const jira = makeJira([issueFor('STATREPS-1', gantt), tombstone]);

    await expect(createSpaceReportsBackend(jira, config).readAll()).resolves.toEqual({ gantt });
    // Silent: a tombstone is expected, not a mangled record.
    expect(console.warn).not.toHaveBeenCalled();
  });

  // `deleted` is an envelope flag, not part of a report — it must never ride along into a later save.
  it('strips the tombstone flag from a report it reads back', async () => {
    const undeleted = { ...gantt, deleted: false } as typeof gantt;
    const jira = makeJira([issueFor('STATREPS-1', undeleted)]);

    const reports = await createSpaceReportsBackend(jira, config).readAll();

    expect(reports.gantt).toEqual(gantt);
    expect(reports.gantt).not.toHaveProperty('deleted');
  });

  it('does nothing when asked to delete a report that is not there', async () => {
    const jira = makeJira();
    const backend = createSpaceReportsBackend(jira, config);

    await expect(backend.remove(gantt, {})).resolves.toBeUndefined();
    expect(jira.editJiraIssueWithNamedFields).not.toHaveBeenCalled();
  });

  // The whole point of the subset: a Reports Space would otherwise pay n edits for one migration.
  it('writes back only the reports a migration actually changed', async () => {
    const jira = makeJira([issueFor('STATREPS-1', gantt), issueFor('STATREPS-2', table)]);
    const backend = createSpaceReportsBackend(jira, config);

    await backend.readAll();
    await backend.writeMigrated([table], { gantt, table });

    expect(jira.editJiraIssueWithNamedFields).toHaveBeenCalledTimes(1);
    expect(jira.editJiraIssueWithNamedFields.mock.calls[0][0]).toBe('STATREPS-2');
  });

  it('escapes a space key so it cannot break out of the JQL string', async () => {
    const jira = makeJira();

    await createSpaceReportsBackend(jira, { spaceName: 'ST"ATS', spaceType: 'Story' }).readAll();

    expect(jira.fetchAllJiraIssuesWithJQL.mock.calls[0][0].jql).toContain('project = "ST\\"ATS"');
  });
});
