name: Destroy prod (Manual)

on:
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - id: destroy
        name: Destroy instance
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_JIRA_INTEGRATIONS}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_JIRA_INTEGRATIONS}}
          aws_default_region: us-east-1
  
          tf_state_bucket_destroy: true
          tf_state_bucket: bitovi-jira-timeline-report-prod-tf-state
          tf_stack_destroy: true
  
          aws_r53_enable: true
          aws_r53_sub_domain_name: timeline-report
          aws_r53_domain_name: bitovi-jira.com
          aws_elb_app_port: 3000
          
          aws_ec2_instance_type: t3.small
          aws_ec2_instance_root_vol_size: 30
  
          # Provide a secret called `DOT_ENV` to append environment variables to the .env file
  
          env_ghs: ${{ secrets.DOT_ENV }}