name: Feature Build

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: build .env
        run: |
          echo "CLIENT_JIRA_CLIENT_ID=${{ secrets.CLIENT_JIRA_CLIENT_ID }}" > .env
          echo "JIRA_CLIENT_SECRET=${{ secrets.JIRA_CLIENT_SECRET }}" >> .env
          echo "JIRA_TOTP_SECRET=${{ secrets.JIRA_TOTP_SECRET }}" >> .env
          echo "CLIENT_JIRA_API_URL=${{ vars.CLIENT_JIRA_API_URL }}" >> .env
          echo "CLIENT_JIRA_CALLBACK_URL=${{ vars.CLIENT_JIRA_CALLBACK_URL }}" >> .env
          echo "CLIENT_JIRA_SCOPE=${{ vars.CLIENT_JIRA_SCOPE }}" >> .env
          echo "PORT=${{ vars.PORT }}"
          echo ".env file created"
          cat .env
          
      - name: Run Build
        run: |
          npm ci
          npm run build

      - name: Commit `dist` Folder to `staging`
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -f public/dist/
          git commit --no-verify -m 'Build artifacts [skip ci]' || echo "No changes to commit"
          git push --force origin HEAD:staging
